export const cinematicTemplate = (data) => `
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${data.title} | Cinematic View</title>
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Outfit:wght@300;600;800&display=swap');
        
        :root {
            --neon-blue: #00f3ff;
            --neon-purple: #bd00ff;
            --bg-color: #050505;
            --glass: rgba(255, 255, 255, 0.05);
        }

        body {
            margin: 0;
            background: var(--bg-color);
            color: white;
            font-family: 'Outfit', sans-serif;
            overflow-x: hidden;
        }

        #canvas-container {
            position: fixed;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            z-index: -1;
            opacity: 0.6;
        }

        .main-content {
            position: relative;
            z-index: 10;
            max-width: 1200px;
            margin: 0 auto;
            padding: 2rem;
        }

        header {
            height: 80vh;
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: flex-start;
        }

        h1 {
            font-size: 5rem;
            line-height: 1;
            margin: 0;
            background: linear-gradient(to right, var(--neon-blue), var(--neon-purple));
            -webkit-background-clip: text;
            -webkit-text-fill-color: transparent;
            text-shadow: 0 0 20px rgba(0, 243, 255, 0.3);
            text-transform: uppercase;
        }

        .subtitle {
            font-size: 1.5rem;
            color: #aaa;
            max-width: 600px;
            margin-top: 1rem;
            line-height: 1.6;
        }

        .btn-glow {
            display: inline-block;
            margin-top: 2rem;
            padding: 1rem 3rem;
            background: transparent;
            border: 1px solid var(--neon-blue);
            color: var(--neon-blue);
            text-decoration: none;
            text-transform: uppercase;
            letter-spacing: 2px;
            font-weight: bold;
            transition: 0.3s;
            box-shadow: 0 0 10px rgba(0, 243, 255, 0.2);
        }

        .btn-glow:hover {
            background: var(--neon-blue);
            color: black;
            box-shadow: 0 0 30px rgba(0, 243, 255, 0.8);
        }

        .features-grid {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
            gap: 2rem;
            margin-top: 4rem;
        }

        .feature-card {
            background: var(--glass);
            backdrop-filter: blur(10px);
            border: 1px solid rgba(255, 255, 255, 0.1);
            padding: 2rem;
            border-radius: 12px;
            transition: transform 0.3s ease;
        }

        .feature-card:hover {
            transform: translateY(-10px);
            border-color: var(--neon-purple);
        }

        .readme-content {
            background: rgba(0,0,0,0.8);
            padding: 3rem;
            margin-top: 5rem;
            border-radius: 20px;
            border: 1px solid rgba(255,255,255,0.1);
        }
        
        .readme-content h1, .readme-content h2 { margin-top: 2rem; }
        .readme-content a { color: var(--neon-blue); }
        .readme-content code { background: #222; padding: 0.2rem 0.5rem; border-radius: 4px; }
        .readme-content pre { background: #111; padding: 1rem; border-radius: 8px; overflow-x: auto; }

    </style>
</head>
<body>
    <div id="canvas-container"></div>

    <div class="main-content">
        <header>
            <div style="font-size: 0.8rem; letter-spacing: 4px; color: var(--neon-purple); margin-bottom: 1rem;">GENERATED BY LUMINA</div>
            <h1>${data.title}</h1>
            <p class="subtitle">${data.description}</p>
            <a href="#readme" class="btn-glow">Explore Docs</a>
        </header>

        <div class="features-grid">
            ${data.features.map(f => `
                <div class="feature-card">
                    <h3 style="color: var(--neon-blue)">⚡ Feature</h3>
                    <p>${f}</p>
                </div>
            `).join('')}
        </div>

        <div id="readme" class="readme-content">
            ${data.contentHtml}
        </div>
        
        <footer style="margin-top: 5rem; padding: 2rem 0; color: #555; text-align: center;">
            <p>Generated with <span style="color:var(--neon-blue)">Lumina CLI</span></p>
        </footer>
    </div>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/three.js/r128/three.min.js"></script>
    <script>
        // THREE.JS CINEMATIC BACKGROUND
        const scene = new THREE.Scene();
        scene.fog = new THREE.FogExp2(0x050505, 0.002);
        
        const camera = new THREE.PerspectiveCamera(75, window.innerWidth / window.innerHeight, 0.1, 1000);
        const renderer = new THREE.WebGLRenderer({ alpha: true });
        renderer.setSize(window.innerWidth, window.innerHeight);
        document.getElementById('canvas-container').appendChild(renderer.domElement);

        // Particles
        const geometry = new THREE.BufferGeometry();
        const vertices = [];
        for (let i = 0; i < 2000; i++) {
            vertices.push((Math.random() - 0.5) * 50); // x
            vertices.push((Math.random() - 0.5) * 50); // y
            vertices.push((Math.random() - 0.5) * 50); // z
        }
        geometry.setAttribute('position', new THREE.Float32BufferAttribute(vertices, 3));
        const material = new THREE.PointsMaterial({ color: 0x00f3ff, size: 0.1, transparent: true, opacity: 0.8 });
        const particles = new THREE.Points(geometry, material);
        scene.add(particles);

        // Floating Icosahedron
        const icoGeo = new THREE.IcosahedronGeometry(10, 1);
        const icoMat = new THREE.MeshBasicMaterial({ color: 0xbd00ff, wireframe: true, transparent: true, opacity: 0.1 });
        const ico = new THREE.Mesh(icoGeo, icoMat);
        scene.add(ico);

        camera.position.z = 20;

        // Animation
        let mouseX = 0;
        let mouseY = 0;
        
        document.addEventListener('mousemove', (e) => {
            mouseX = e.clientX / window.innerWidth - 0.5;
            mouseY = e.clientY / window.innerHeight - 0.5;
        });

        function animate() {
            requestAnimationFrame(animate);
            
            particles.rotation.y += 0.001;
            particles.rotation.x += 0.001;
            
            ico.rotation.y -= 0.002;
            ico.rotation.x -= 0.002;

            // Parallax
            camera.position.x += (mouseX * 5 - camera.position.x) * 0.05;
            camera.position.y += (-mouseY * 5 - camera.position.y) * 0.05;

            renderer.render(scene, camera);
        }
        animate();

        // Resize
        window.addEventListener('resize', () => {
            camera.aspect = window.innerWidth / window.innerHeight;
            camera.updateProjectionMatrix();
            renderer.setSize(window.innerWidth, window.innerHeight);
        });
    </script>
</body>
</html>
`;
